insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Innojam', '48297 Park Meadow Center', '613648', 'Stulovo');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Skajo', '0565 Pepper Wood Parkway', '517 01', 'Solnice');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Divape', '928 Nancy Alley', 4215, 'Liuhu');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Jabbersphere', '89 Scott Lane', 340388, 'Socota');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Ooba', '79809 Myrtle Parkway', '75498', 'La Soledad');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Oyondu', '80 Granby Terrace', 204112, 'Daxi');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Twitterwire', '3 Waxwing Center', 297966, 'Hexi');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Quimm', '01857 Arapahoe Hill', 468891, 'Sepolong Timur');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Eayo', '5018 Eastlawn Center', '5014', 'Quipot');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Jabbersphere', '20984 Ramsey Hill', 562244, 'San Lorenzo');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Jaxspan', '6 Havey Street', '89-412', 'Sośno');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Mynte', '0907 Claremont Junction', 191154, 'Potrerillos Arriba');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Photospace', '9 Forster Junction', '2870-013', 'Afonsoeiro');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Devcast', '43623 Forest Run Road', '989-2474', 'Asahi');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Buzzdog', '4330 Prairieview Place', '69115-000', 'Rio Preto da Eva');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Ooba', '7 Ruskin Lane', 456339, 'Pochayiv');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('BlogXS', '8 Golf View Place', 423583, 'Huji');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Tambee', '402 Carioca Hill', '2430-482', 'São Pedro de Muel');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Thoughtbeat', '114 Grasskamp Way', 43211, 'Jiashi');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Meejo', '4 Holmberg Junction', 284070, 'Asahbadung');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Tagfeed', '135 Butterfield Lane', 409315, 'Tizguine');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Devpoint', '215 Eggendart Road', '0472', 'Oslo');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Realfire', '0937 Ridgeway Court', 796174, 'Klina');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Aimbo', '76005 Loeprich Pass', 766305, 'La Mesa');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Riffwire', '2 Talisman Parkway', 541328, 'Jiancheng');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Realcube', '676 Homewood Terrace', '3019', 'Marilao');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Buzzster', '2 Randy Parkway', '13920-000', 'Pedreira');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Fivespan', '3 Shopko Park', 565780, 'Veguitas');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Pixope', '52743 Sycamore Way', 366868, 'Peñaflor');
insert into asiakas (yritys, laskutusosoite, postinumero, postitoimipaikka) values ('Fivebridge', '578 Main Avenue', 50295, 'Delok');
