insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Mercedes-Benz', 'CLK-Class', 2000, 8, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('MINI', 'Cooper', 2005, 26, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Toyota', 'Celica', 1994, 5, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Mazda', 'MX-5', 2001, 30, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Plymouth', 'Voyager', 1999, 1, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Mazda', '929', 1994, 15, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('GMC', 'Yukon XL 1500', 2001, 14, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Suzuki', 'Kizashi', 2010, 22, 'Nostimet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Volvo', 'XC90', 2003, 29, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Infiniti', 'G', 2004, 25, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('BMW', '7 Series', 1998, 27, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Ford', 'F-250 Super Duty', 2006, 10, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Mazda', 'MX-5', 1995, 8, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Mazda', 'Mazda3', 2007, 11, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Dodge', 'Viper', 2006, 12, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Volkswagen', 'Jetta', 2009, 21, 'Nostimet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Studebaker', 'Avanti', 1962, 16, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Mazda', 'RX-7', 1984, 21, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Land Rover', 'Discovery', 1999, 24, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Saab', '9-5', 2001, 19, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Plymouth', 'Grand Voyager', 2000, 17, 'Nostimet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Subaru', 'Impreza WRX', 2011, 28, 'Nostimet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Pontiac', 'Trans Sport', 1999, 30, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Aptera', '2e', 2009, 9, 'Nostimet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Nissan', 'Frontier', 2006, 8, 'Nostimet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Saab', '9-5', 2000, 4, 'Nostimet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Chevrolet', 'Silverado', 2011, 26, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Cadillac', 'Allante', 1992, 10, 'Telineet');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Ford', 'Club Wagon', 1996, 24, 'Sähkötyökalut');
insert into tuote (nimike, merkki, malli, paivavuokra, tuoteryhma) values ('Chevrolet', 'Uplander', 2007, 13, 'Telineet');
